name: codacy-coverage-reporter

on: ["push"]

jobs:
  codacy-coverage-reporter:
    runs-on: windows-latest
    name: codacy-coverage-reporter
    steps:
    
      - uses: actions/checkout@v2
    
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.*

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore
        
      - name: Cover
        run: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=coverage /p:IncludeTestAssembly=true --no-restore
      
      - name: Populate Reports Variable
        shell: pwsh
        run: |
          $ReportPaths = Get-ChildItem *cobertura.xml -Recurse | Resolve-Path -Relative | Join-String -Separator ","
          echo "COVERAGE_REPORTS=$ReportPaths" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
    
      - name: "Set Repository Variables"
        shell: bash
        run: |
          echo "CODACY_ORGANIZATION_PROVIDER=$(if [[ $GITHUB_SERVER_URL == "https://github.com" ]]; then echo "gh"; else echo "ghe"; fi)" >> $GITHUB_ENV
          echo "CODACY_USERNAME=$(echo $GITHUB_REPOSITORY | cut -d '/' -f 1)" >> $GITHUB_ENV
          echo "CODACY_PROJECT_NAME=$(echo $GITHUB_REPOSITORY | cut -d '/' -f 2)" >> $GITHUB_ENV

      - name: Upload Coverage to Codacy
        shell: bash
        run: bash <(curl -Ls https://coverage.codacy.com/get.sh) report -l CSharp $(find . -name 'coverage.cobertura.xml' -printf '-r %p ')
        env:
          CODACY_API_TOKEN: ${{ secrets.CODACY_API_TOKEN }}
#           CODACY_USERNAME: ${{ secrets.CODACY_USERNAME }}
      
#       - name: Run codacy-coverage-reporter
#         uses: codacy/codacy-coverage-reporter-action@v1
#         with:
#           api-token: ${{ secrets.CODACY_API_TOKEN }}
#           coverage-reports: '$($Env:COVERAGE_REPORTS)'
