name: codacy-coverage-reporter-templated

on: ["push", "workflow_dispatch"]


jobs:
  codacy-coverage-reporter:
    name: codacy-coverage-reporter    
    uses: bortington/github-common/.github/workflows/dotnet-test-with-codacy.yml@main
    with:
      dotnet_version: 6.0.*
    secrets:
      registry_username: ${{secrets.CODACY_API_TOKEN }}
