name: codacy-coverage-reporter-templated

on: ["push", "workflow_dispatch"]


jobs:
  codacy-coverage-reporter:
    uses: bortington/github-common/.github/workflows/dotnet-test-with-codacy.yml@dotnet-test-with-codacy/v1
    with:
      dotnet-version: 6.0.*
    secrets:
      CODACY_API_TOKEN: ${{secrets.CODACY_API_TOKEN }}
