name: codacy-coverage-reporter-templated

on: ["push", "workflow_dispatch"]


jobs:
  codacy-coverage-reporter:
    uses: bortington/github-common/.github/workflows/dotnet-test-with-codacy.yml@252ef4d840c5262bfa4e0ba182421890de7ad299
    with:
      dotnet-version: 6.0.*
      runs-on: windows-latest
    secrets:
      CODACY_API_TOKEN: ${{secrets.CODACY_API_TOKEN }}
