name: codacy-coverage-reporter-templated

on: ["push", "workflow_dispatch"]

jobs:
  codacy-coverage-reporter:
    runs-on: windows-latest
    name: codacy-coverage-reporter    
    steps:    
      - uses: bortington/.github/blob/main/workflows/dotnet-test-with-codacy.yml
        with:
          dotnet_version: 6.0.*
        secrets:
          registry_username: ${{secrets.CODACY_API_TOKEN }}
